spring:
  datasource:
    url: jdbc:mysql://localhost:3306/message?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  thymeleaf:
    prefix: classpath:/templates/

# 메일 서버 설정
  mail:
    host: smtp.naver.com
    port: 587
    username: amy9047@naver.com
    password: 1q2w3e4r!!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
